package pepe.test;
// Generated by ComTest BEGIN
import java.util.*;
import static org.junit.Assert.*;
import org.junit.*;
import pepe.*;
// Generated by ComTest END

/**
 * Test class made by ComTest
 * @version 2020.04.23 02:58:15 // Generated by ComTest
 *
 */
@SuppressWarnings({ "all" })
public class AlustatTest {


  // Generated by ComTest BEGIN
  /** testAnnaAlusta115 */
  @Test
  public void testAnnaAlusta115() {    // Alustat: 115
    Alustat alustat = new Alustat(); 
    Alusta a1 = new Alusta(); alustat.lisaa(a1); 
    Alusta a2 = new Alusta(); alustat.lisaa(a2); 
    a1.rekisteroi(); a1.taytaAlustaTiedoilla(); 
    a2.rekisteroi(); a2.taytaAlustaTiedoilla(); 
    assertEquals("From: Alustat line: 124", a1.getTunniste(), alustat.annaAlusta(a1.getTunniste()).getTunniste()); 
    assertEquals("From: Alustat line: 125", a2.getTunniste(), alustat.annaAlusta(a2.getTunniste()).getTunniste()); 
  } // Generated by ComTest END
}