package pepe.test;
// Generated by ComTest BEGIN
import static org.junit.Assert.*;
import org.junit.*;
import pepe.*;
// Generated by ComTest END

/**
 * Test class made by ComTest
 * @version 2020.04.23 03:14:17 // Generated by ComTest
 *
 */
@SuppressWarnings({ "all" })
public class KuntoTest {



  // Generated by ComTest BEGIN
  /** testHaeLuokitus43 */
  @Test
  public void testHaeLuokitus43() {    // Kunto: 43
    Kunto luokitukset = new Kunto(); 
    assertEquals("From: Kunto line: 45", "MINT", luokitukset.haeLuokitus(3).toString()); 
    assertEquals("From: Kunto line: 46", "OK", luokitukset.haeLuokitus(2).toString()); 
    assertEquals("From: Kunto line: 47", "HUONO", luokitukset.haeLuokitus(1).toString()); 
  } // Generated by ComTest END
}