package pepe.test;
// Generated by ComTest BEGIN
import pepe.*;
import java.util.*;
import static org.junit.Assert.*;
import org.junit.*;
// Generated by ComTest END

/**
 * Test class made by ComTest
 * @version 2020.04.23 04:14:40 // Generated by ComTest
 *
 */
@SuppressWarnings({ "all" })
public class PelitTest {


  // Generated by ComTest BEGIN
  /** testIterator105 */
  @Test
  public void testIterator105() {    // Pelit: 105
    Pelit pelit = new Pelit(); 
    Peli p21 = new Peli(1); pelit.lisaa(p21); 
    Peli p11 = new Peli(2); pelit.lisaa(p11); 
    Peli p22 = new Peli(3); pelit.lisaa(p22); 
    Peli p12 = new Peli(4); pelit.lisaa(p12); 
    Peli p23 = new Peli(5); pelit.lisaa(p23); 
    Iterator<Peli> i2=pelit.iterator(); 
    assertEquals("From: Pelit line: 117", p21, i2.next()); 
    assertEquals("From: Pelit line: 118", p11, i2.next()); 
    assertEquals("From: Pelit line: 119", p22, i2.next()); 
    assertEquals("From: Pelit line: 120", p12, i2.next()); 
    assertEquals("From: Pelit line: 121", p23, i2.next()); 
    try {
    assertEquals("From: Pelit line: 122", p12, i2.next()); 
    fail("Pelit: 122 Did not throw NoSuchElementException");
    } catch(NoSuchElementException _e_){ _e_.getMessage(); }
    int n = 0; 
    int pnrot[] = { 1,2,3,4,5} ; 
    for ( Peli peli:pelit ) {
    assertEquals("From: Pelit line: 128", pnrot[n], peli.getTunniste()); n++; 
    }
    assertEquals("From: Pelit line: 131", 5, n); 
  } // Generated by ComTest END
}