package pepe.test;
// Generated by ComTest BEGIN
import static org.junit.Assert.*;
import org.junit.*;
import pepe.*;
// Generated by ComTest END

/**
 * Test class made by ComTest
 * @version 2020.04.23 11:07:12 // Generated by ComTest
 *
 */
@SuppressWarnings({ "all" })
public class PeliTest {



  // Generated by ComTest BEGIN
  /** testRekisteroi140 */
  @Test
  public void testRekisteroi140() {    // Peli: 140
    Peli ra1 = new Peli(); 
    assertEquals("From: Peli line: 142", 0, ra1.getTunniste()); 
    ra1.rekisteroi(); 
    Peli ra2 = new Peli(); 
    ra2.rekisteroi(); 
    int n1 = ra1.getTunniste(); 
    int n2 = ra2.getTunniste(); 
    assertEquals("From: Peli line: 148", n2-1, n1); 
  } // Generated by ComTest END


  // Generated by ComTest BEGIN
  /** testTarkista342 */
  @Test
  public void testTarkista342() {    // Peli: 342
    Peli peli = new Peli(); 
    assertEquals("From: Peli line: 344", false, peli.tarkista("|")); 
    assertEquals("From: Peli line: 345", false, peli.tarkista("")); 
    assertEquals("From: Peli line: 346", false, peli.tarkista("merkkijono|")); 
    assertEquals("From: Peli line: 347", true, peli.tarkista("merkkijono")); 
  } // Generated by ComTest END


  // Generated by ComTest BEGIN
  /** testTarkistaJulkaisuvuosi367 */
  @Test
  public void testTarkistaJulkaisuvuosi367() {    // Peli: 367
    Peli peli = new Peli(); 
    peli.setHankintavuosi(2000); 
    assertEquals("From: Peli line: 370", false, peli.tarkistaJulkaisuvuosi("")); 
    assertEquals("From: Peli line: 371", false, peli.tarkistaJulkaisuvuosi("0")); 
    assertEquals("From: Peli line: 372", false, peli.tarkistaJulkaisuvuosi("0000")); 
    assertEquals("From: Peli line: 373", false, peli.tarkistaJulkaisuvuosi("2020")); 
    assertEquals("From: Peli line: 374", true, peli.tarkistaJulkaisuvuosi("1998")); 
    assertEquals("From: Peli line: 375", true, peli.tarkistaJulkaisuvuosi("1982")); 
    peli.setJulkaisuvuosi(2020); 
    assertEquals("From: Peli line: 378", false, peli.tarkistaHankintavuosi("")); 
    assertEquals("From: Peli line: 379", false, peli.tarkistaHankintavuosi("0")); 
    assertEquals("From: Peli line: 380", false, peli.tarkistaHankintavuosi("0000")); 
    assertEquals("From: Peli line: 381", false, peli.tarkistaHankintavuosi("1999")); 
    assertEquals("From: Peli line: 382", true, peli.tarkistaHankintavuosi("2020")); 
  } // Generated by ComTest END
}