package pepe.test;
// Generated by ComTest BEGIN
import static org.junit.Assert.*;
import org.junit.*;
import fxPepe.SailoException;
import pepe.*;
// Generated by ComTest END

/**
 * Test class made by ComTest
 * @version 2020.04.23 04:59:45 // Generated by ComTest
 *
 */
@SuppressWarnings({ "all" })
public class PepeTest {



  // Generated by ComTest BEGIN
  /** 
   * testAnnaSamatNimikkeet105 
   * @throws SailoException when error
   */
  @Test
  public void testAnnaSamatNimikkeet105() throws SailoException {    // Pepe: 105
    Pepe pepe = new Pepe(); 
    Pelit pelit = new Pelit(); 
    Nimikkeet nimikkeet = new Nimikkeet(); 
    Nimike n1 = new Nimike(); 
    n1.rekisteroi(); 
    n1.taytaTestiNimikeTiedoilla(); 
    nimikkeet.lisaa(n1); 
    Peli p1 = new Peli(); 
    Peli p2 = new Peli(); 
    Peli p3 = new Peli(); 
    p1.rekisteroi(); 
    p2.rekisteroi(); 
    p3.rekisteroi(); 
    p1.taytaTestiPeliTiedoilla(n1.getTunniste(), 0); 
    p2.taytaTestiPeliTiedoilla(n1.getTunniste(), 0); 
    p3.taytaTestiPeliTiedoilla(n1.getTunniste(), 0); 
    pelit.lisaa(p1); 
    pelit.lisaa(p2); 
    pelit.lisaa(p3); 
    p1.setNimike(n1.getTunniste()); 
    p2.setNimike(n1.getTunniste()); 
    p3.setNimike(n1.getTunniste()); 
    assertEquals("From: Pepe line: 130", 0, pepe.annaSamatNimikkeet(p1)); 
    assertEquals("From: Pepe line: 131", 0, pepe.annaSamatNimikkeet(p2)); 
    assertEquals("From: Pepe line: 132", 0, pepe.annaSamatNimikkeet(p3)); 
  } // Generated by ComTest END
}