package pepe.test;
// Generated by ComTest BEGIN
import static org.junit.Assert.*;
import org.junit.*;
import fxPepe.SailoException;
import pepe.*;
// Generated by ComTest END

/**
 * Test class made by ComTest
 * @version 2020.04.23 05:06:20 // Generated by ComTest
 *
 */
@SuppressWarnings({ "all" })
public class PepeTest {



  // Generated by ComTest BEGIN
  /** 
   * testAnnaSamatNimikkeet105 
   * @throws SailoException when error
   */
  @Test
  public void testAnnaSamatNimikkeet105() throws SailoException {    // Pepe: 105
    Pepe pepe = new Pepe(); 
    Nimike n1 = new Nimike(); 
    n1.rekisteroi(); 
    n1.taytaTestiNimikeTiedoilla(); 
    pepe.lisaa(n1); 
    Peli p1 = new Peli(); 
    Peli p2 = new Peli(); 
    Peli p3 = new Peli(); 
    p1.rekisteroi(); 
    p2.rekisteroi(); 
    p3.rekisteroi(); 
    p1.taytaTestiPeliTiedoilla(n1.getTunniste(), 0); 
    p2.taytaTestiPeliTiedoilla(n1.getTunniste(), 0); 
    p3.taytaTestiPeliTiedoilla(n1.getTunniste(), 0); 
    pepe.lisaa(p1); 
    pepe.lisaa(p2); 
    pepe.lisaa(p3); 
    assertEquals("From: Pepe line: 127", 3, pepe.annaSamatNimikkeet(p1)); 
    pepe.poista(p1); 
    assertEquals("From: Pepe line: 129", 2, pepe.annaSamatNimikkeet(p2)); 
    pepe.poista(p2); 
    assertEquals("From: Pepe line: 131", 1, pepe.annaSamatNimikkeet(p3)); 
  } // Generated by ComTest END
}