package fxPepe.test;
// Generated by ComTest BEGIN
import fxPepe.*;
import java.util.*;
import static org.junit.Assert.*;
import org.junit.*;
// Generated by ComTest END

/**
 * Test class made by ComTest
 * @version 2020.03.17 02:53:28 // Generated by ComTest
 *
 */
@SuppressWarnings({ "all" })
public class AlustatTest {


  // Generated by ComTest BEGIN
  /** testIterator74 */
  @Test
  public void testIterator74() {    // Alustat: 74
    PeliTiedot tiedot = new PeliTiedot(); 
    PeliTieto tieto21 = new PeliTieto(2); tiedot.lisaa(tieto21); 
    PeliTieto tieto11 = new PeliTieto(1); tiedot.lisaa(tieto11); 
    PeliTieto tieto22 = new PeliTieto(2); tiedot.lisaa(tieto22); 
    PeliTieto tieto12 = new PeliTieto(1); tiedot.lisaa(tieto12); 
    PeliTieto tieto23 = new PeliTieto(2); tiedot.lisaa(tieto23); 
    Iterator<PeliTieto> i2=tiedot.iterator(); 
    assertEquals("From: Alustat line: 86", tieto21, i2.next()); 
    assertEquals("From: Alustat line: 87", tieto11, i2.next()); 
    assertEquals("From: Alustat line: 88", tieto22, i2.next()); 
    assertEquals("From: Alustat line: 89", tieto12, i2.next()); 
    assertEquals("From: Alustat line: 90", tieto23, i2.next()); 
    try {
    assertEquals("From: Alustat line: 91", tieto12, i2.next()); 
    fail("Alustat: 91 Did not throw NoSuchElementException");
    } catch(NoSuchElementException _e_){ _e_.getMessage(); }
    int n = 0; 
    int pnrot[] = { 2,1,2,1,2} ; 
    for ( PeliTieto tieto:tiedot ) {
    assertEquals("From: Alustat line: 97", pnrot[n], tieto.getPelinTunniste()); n++; 
    }
    assertEquals("From: Alustat line: 100", 5, n); 
  } // Generated by ComTest END


  // Generated by ComTest BEGIN
  /** testAnnaAlustaTiedot116 */
  @Test
  public void testAnnaAlustaTiedot116() {    // Alustat: 116
    PeliTiedot tiedot = new PeliTiedot(); 
    PeliTieto tieto21 = new PeliTieto(2); tiedot.lisaa(tieto21); 
    PeliTieto tieto11 = new PeliTieto(1); tiedot.lisaa(tieto11); 
    PeliTieto tieto22 = new PeliTieto(2); tiedot.lisaa(tieto22); 
    PeliTieto tieto12 = new PeliTieto(1); tiedot.lisaa(tieto12); 
    PeliTieto tieto23 = new PeliTieto(2); tiedot.lisaa(tieto23); 
    PeliTieto tieto51 = new PeliTieto(5); tiedot.lisaa(tieto51); 
    List<PeliTieto> loytyneet; 
    loytyneet = tiedot.annaPeliTiedot(3); 
    assertEquals("From: Alustat line: 129", 0, loytyneet.size()); 
    loytyneet = tiedot.annaPeliTiedot(1); 
    assertEquals("From: Alustat line: 131", 2, loytyneet.size()); 
    assertEquals("From: Alustat line: 132", true, loytyneet.get(0) == tieto11); 
    assertEquals("From: Alustat line: 133", true, loytyneet.get(1) == tieto12); 
    loytyneet = tiedot.annaPeliTiedot(5); 
    assertEquals("From: Alustat line: 135", 1, loytyneet.size()); 
    assertEquals("From: Alustat line: 136", true, loytyneet.get(0) == tieto51); 
  } // Generated by ComTest END
}