package fxPepe.test;
// Generated by ComTest BEGIN
import static org.junit.Assert.*;
import org.junit.*;
import fxPepe.*;
// Generated by ComTest END

/**
 * Test class made by ComTest
 * @version 2020.03.17 02:53:20 // Generated by ComTest
 *
 */
@SuppressWarnings({ "all" })
public class AlustaTest {



  // Generated by ComTest BEGIN
  /** testRekisteroi103 */
  @Test
  public void testRekisteroi103() {    // Alusta: 103
    Alusta a1 = new Alusta(); 
    assertEquals("From: Alusta line: 105", 0, a1.getAlustanTunniste()); 
    a1.rekisteroi(); 
    Alusta a2 = new Alusta(); 
    a2.rekisteroi(); 
    int n1 = a1.getAlustanTunniste(); 
    int n2 = a2.getAlustanTunniste(); 
    assertEquals("From: Alusta line: 111", n2-1, n1); 
  } // Generated by ComTest END
}