package fxPepe.test;
// Generated by ComTest BEGIN
import static org.junit.Assert.*;
import org.junit.*;
import fxPepe.*;
// Generated by ComTest END

/**
 * Test class made by ComTest
 * @version 2020.03.16 18:58:18 // Generated by ComTest
 *
 */
@SuppressWarnings({ "all" })
public class AlustatTest {



  // Generated by ComTest BEGIN
  /** 
   * testLisaa32 
   * @throws SailoException when error
   */
  @Test
  public void testLisaa32() throws SailoException {    // Alustat: 32
    Alustat alustat = new Alustat(); 
    Alusta a1 = new Alusta(), a2 = new Alusta(); 
    assertEquals("From: Alustat line: 36", 0, alustat.getLkm()); 
    alustat.lisaa(a1); 
    assertEquals("From: Alustat line: 38", 1, alustat.getLkm()); 
    alustat.lisaa(a2); assertEquals("From: Alustat line: 39", 2, alustat.getLkm()); 
    alustat.lisaa(a1); assertEquals("From: Alustat line: 40", 3, alustat.getLkm()); 
    assertEquals("From: Alustat line: 41", a1, alustat.anna(0)); 
    assertEquals("From: Alustat line: 42", a2, alustat.anna(1)); 
    assertEquals("From: Alustat line: 43", a1, alustat.anna(2)); 
    assertEquals("From: Alustat line: 44", false, alustat.anna(1) == a1); 
    assertEquals("From: Alustat line: 45", true, alustat.anna(1) == a2); 
    try {
    assertEquals("From: Alustat line: 46", a1, alustat.anna(3)); 
    fail("Alustat: 46 Did not throw IndexOutOfBoundsException");
    } catch(IndexOutOfBoundsException _e_){ _e_.getMessage(); }
    alustat.lisaa(a1); assertEquals("From: Alustat line: 47", 4, alustat.getLkm()); 
    alustat.lisaa(a1); assertEquals("From: Alustat line: 48", 5, alustat.getLkm()); 
    try {
    alustat.lisaa(a1); 
    fail("Alustat: 49 Did not throw SailoException");
    } catch(SailoException _e_){ _e_.getMessage(); }
  } // Generated by ComTest END
}