package fxPepe.test;
// Generated by ComTest BEGIN
import fxPepe.*;
import java.util.*;
import static org.junit.Assert.*;
import org.junit.*;
// Generated by ComTest END

/**
 * Test class made by ComTest
 * @version 2020.03.18 21:12:32 // Generated by ComTest
 *
 */
@SuppressWarnings({ "all" })
public class AlustatTest {



  // Generated by ComTest BEGIN
  /** testIterator74 */
  @Test
  public void testIterator74() {    // Alustat: 74
    Alustat alustat = new Alustat(); 
    Alusta alusta21 = new Alusta(1); alustat.lisaa(alusta21); 
    Alusta alusta11 = new Alusta(2); alustat.lisaa(alusta11); 
    Alusta alusta22 = new Alusta(3); alustat.lisaa(alusta22); 
    Alusta alusta12 = new Alusta(4); alustat.lisaa(alusta12); 
    Alusta alusta23 = new Alusta(5); alustat.lisaa(alusta23); 
    Iterator<Alusta> i2=alustat.iterator(); 
    assertEquals("From: Alustat line: 86", alusta21, i2.next()); 
    assertEquals("From: Alustat line: 87", alusta11, i2.next()); 
    assertEquals("From: Alustat line: 88", alusta22, i2.next()); 
    assertEquals("From: Alustat line: 89", alusta12, i2.next()); 
    assertEquals("From: Alustat line: 90", alusta23, i2.next()); 
    try {
    assertEquals("From: Alustat line: 91", alusta11, i2.next()); 
    fail("Alustat: 91 Did not throw NoSuchElementException");
    } catch(NoSuchElementException _e_){ _e_.getMessage(); }
    int n = 0; 
    int anrot[] = { 1,2,3,4,5} ; 
    for (Alusta alusta:alustat) {
    assertEquals("From: Alustat line: 97", anrot[n], alusta.getTunniste()); n++; 
    }
    assertEquals("From: Alustat line: 100", 5, n); 
  } // Generated by ComTest END


  // Generated by ComTest BEGIN
  /** testAnnaAlusta115 */
  @Test
  public void testAnnaAlusta115() {    // Alustat: 115
    Alustat alustat = new Alustat(); 
    Alusta a1 = new Alusta(); alustat.lisaa(a1); 
    Alusta a2 = new Alusta(); alustat.lisaa(a2); 
    a1.rekisteroi(); a1.taytaAlustaTiedoilla(); 
    a2.rekisteroi(); a2.taytaAlustaTiedoilla(); 
    assertEquals("From: Alustat line: 124", a1.getTunniste(), alustat.annaAlusta(a1.getTunniste()).getTunniste()); 
    assertEquals("From: Alustat line: 125", a2.getTunniste(), alustat.annaAlusta(a2.getTunniste()).getTunniste()); 
  } // Generated by ComTest END
}