package fxPepe.test;
// Generated by ComTest BEGIN
import static org.junit.Assert.*;
import org.junit.*;
import fxPepe.*;
// Generated by ComTest END

/**
 * Test class made by ComTest
 * @version 2020.03.16 18:49:34 // Generated by ComTest
 *
 */
@SuppressWarnings({ "all" })
public class AlustaTest {



  // Generated by ComTest BEGIN
  /** testGetNimi29 */
  @Test
  public void testGetNimi29() {    // Alusta: 29
    Alusta a = new Alusta(); 
    a.taytaAlustaTiedoilla(); 
    { String _l_=a.getNimi(),_r_="PlayStation 1"; if ( !_l_.matches(_r_) ) fail("From: Alusta line: 32" + " does not match: ["+ _l_ + "] != [" + _r_ + "]");}
    { String _l_=a.getLyhenne(),_r_="PS1"; if ( !_l_.matches(_r_) ) fail("From: Alusta line: 33" + " does not match: ["+ _l_ + "] != [" + _r_ + "]");}
  } // Generated by ComTest END


  // Generated by ComTest BEGIN
  /** testGetLyhenne44 */
  @Test
  public void testGetLyhenne44() {    // Alusta: 44
    Alusta a = new Alusta(); 
    a.taytaAlustaTiedoilla(); 
    { String _l_=a.getLyhenne(),_r_="PS1"; if ( !_l_.matches(_r_) ) fail("From: Alusta line: 47" + " does not match: ["+ _l_ + "] != [" + _r_ + "]");}
  } // Generated by ComTest END


  // Generated by ComTest BEGIN
  /** testRekisteroi131 */
  @Test
  public void testRekisteroi131() {    // Alusta: 131
    Alusta a1 = new Alusta(); 
    assertEquals("From: Alusta line: 133", 0, a1.getTunniste()); 
    a1.rekisteroi(); 
    Alusta a2 = new Alusta(); 
    a2.rekisteroi(); 
    int n1 = a1.getTunniste(); 
    int n2 = a2.getTunniste(); 
    assertEquals("From: Alusta line: 139", n2-1, n1); 
  } // Generated by ComTest END
}