package fxPepe.test;
// Generated by ComTest BEGIN
import static org.junit.Assert.*;
import org.junit.*;
import fxPepe.*;
// Generated by ComTest END

/**
 * Test class made by ComTest
 * @version 2020.03.18 23:01:41 // Generated by ComTest
 *
 */
@SuppressWarnings({ "all" })
public class NimikkeetTest {


  // Generated by ComTest BEGIN
  /** 
   * testLisaa32 
   * @throws SailoException when error
   */
  @Test
  public void testLisaa32() throws SailoException {    // Nimikkeet: 32
    Nimikkeet nimikkeet = new Nimikkeet(); 
    Nimike cnc = new Nimike(), ra = new Nimike(); 
    assertEquals("From: Nimikkeet line: 36", 0, nimikkeet.getLkm()); 
    nimikkeet.lisaa(cnc); assertEquals("From: Nimikkeet line: 37", 1, nimikkeet.getLkm()); 
    nimikkeet.lisaa(ra); assertEquals("From: Nimikkeet line: 38", 2, nimikkeet.getLkm()); 
    nimikkeet.lisaa(cnc); assertEquals("From: Nimikkeet line: 39", 3, nimikkeet.getLkm()); 
    assertEquals("From: Nimikkeet line: 40", cnc, nimikkeet.anna(0)); 
    assertEquals("From: Nimikkeet line: 41", ra, nimikkeet.anna(1)); 
    assertEquals("From: Nimikkeet line: 42", cnc, nimikkeet.anna(2)); 
    assertEquals("From: Nimikkeet line: 43", false, nimikkeet.anna(1) == cnc); 
    assertEquals("From: Nimikkeet line: 44", true, nimikkeet.anna(1) == ra); 
    try {
    assertEquals("From: Nimikkeet line: 45", cnc, nimikkeet.anna(3)); 
    fail("Nimikkeet: 45 Did not throw IndexOutOfBoundsException");
    } catch(IndexOutOfBoundsException _e_){ _e_.getMessage(); }
    nimikkeet.lisaa(cnc); assertEquals("From: Nimikkeet line: 46", 4, nimikkeet.getLkm()); 
    nimikkeet.lisaa(cnc); assertEquals("From: Nimikkeet line: 47", 5, nimikkeet.getLkm()); 
    try {
    nimikkeet.lisaa(cnc); 
    fail("Nimikkeet: 48 Did not throw SailoException");
    } catch(SailoException _e_){ _e_.getMessage(); }
  } // Generated by ComTest END
}