package fxPepe.test;
// Generated by ComTest BEGIN
import static org.junit.Assert.*;
import org.junit.*;
import fxPepe.*;
// Generated by ComTest END

/**
 * Test class made by ComTest
 * @version 2020.03.18 19:37:01 // Generated by ComTest
 *
 */
@SuppressWarnings({ "all" })
public class NimikeTest {


  // Generated by ComTest BEGIN
  /** testGetNimi29 */
  @Test
  public void testGetNimi29() {    // Nimike: 29
    Nimike tr2 = new Nimike(); 
    tr2.taytaNimikeTiedoilla(); 
    { String _l_=tr2.getNimi(),_r_="Tomb Raider 2"; if ( !_l_.matches(_r_) ) fail("From: Nimike line: 32" + " does not match: ["+ _l_ + "] != [" + _r_ + "]");}
  } // Generated by ComTest END


  // Generated by ComTest BEGIN
  /** testRekisteroi81 */
  @Test
  public void testRekisteroi81() {    // Nimike: 81
    Nimike n1 = new Nimike(); 
    assertEquals("From: Nimike line: 83", 0, n1.getTunniste()); 
    n1.rekisteroi(); 
    Nimike n2 = new Nimike(); 
    n2.rekisteroi(); 
    int nimi1 = n1.getTunniste(); 
    int nimi2 = n2.getTunniste(); 
    assertEquals("From: Nimike line: 89", nimi2-1, nimi1); 
  } // Generated by ComTest END
}