package fxPepe.test;
// Generated by ComTest BEGIN
import fxPepe.*;
import java.util.*;
import static org.junit.Assert.*;
import org.junit.*;
// Generated by ComTest END

/**
 * Test class made by ComTest
 * @version 2020.03.20 13:31:04 // Generated by ComTest
 *
 */
@SuppressWarnings({ "all" })
public class PelitTest {



  // Generated by ComTest BEGIN
  /** testIterator74 */
  @Test
  public void testIterator74() {    // Pelit: 74
    Pelit pelit = new Pelit(); 
    Peli p21 = new Peli(1); pelit.lisaa(p21); 
    Peli p11 = new Peli(2); pelit.lisaa(p11); 
    Peli p22 = new Peli(3); pelit.lisaa(p22); 
    Peli p12 = new Peli(4); pelit.lisaa(p12); 
    Peli p23 = new Peli(5); pelit.lisaa(p23); 
    Iterator<Peli> i2=pelit.iterator(); 
    assertEquals("From: Pelit line: 86", p21, i2.next()); 
    assertEquals("From: Pelit line: 87", p11, i2.next()); 
    assertEquals("From: Pelit line: 88", p22, i2.next()); 
    assertEquals("From: Pelit line: 89", p12, i2.next()); 
    assertEquals("From: Pelit line: 90", p23, i2.next()); 
    try {
    assertEquals("From: Pelit line: 91", p12, i2.next()); 
    fail("Pelit: 91 Did not throw NoSuchElementException");
    } catch(NoSuchElementException _e_){ _e_.getMessage(); }
    int n = 0; 
    int pnrot[] = { 1,2,3,4,5} ; 
    for ( Peli peli:pelit ) {
    assertEquals("From: Pelit line: 97", pnrot[n], peli.getTunniste()); n++; 
    }
    assertEquals("From: Pelit line: 100", 5, n); 
  } // Generated by ComTest END


  // Generated by ComTest BEGIN
  /** testAnnaPeli116 */
  @Test
  public void testAnnaPeli116() {    // Pelit: 116
    Pelit pelit = new Pelit(); 
    Peli peli21 = new Peli(); 
    peli21.rekisteroi(); 
    peli21.taytaPeliTiedoilla(); 
    pelit.lisaa(peli21); 
    Peli peli11 = new Peli(); 
    peli11.rekisteroi(); 
    peli11.taytaPeliTiedoilla(); 
    pelit.lisaa(peli11); 
    Peli peli12 = new Peli(); 
    peli12.rekisteroi(); 
    peli12.taytaPeliTiedoilla(); 
    pelit.lisaa(peli12); 
    Peli peli25 = new Peli(); 
    peli25.rekisteroi(); 
    peli25.taytaPeliTiedoilla(); 
    pelit.lisaa(peli25); 
    Peli peli51 = new Peli(); 
    peli51.rekisteroi(); 
    peli51.taytaPeliTiedoilla(); 
    pelit.lisaa(peli51); 
    List<Peli> loytyneet; 
    loytyneet = pelit.annaPeli(1); 
    assertEquals("From: Pelit line: 148", 1, loytyneet.size()); 
    loytyneet = pelit.annaPeli(2); 
    assertEquals("From: Pelit line: 150", 1, loytyneet.size()); 
    assertEquals("From: Pelit line: 151", true, loytyneet.get(0) == peli11); 
    loytyneet = pelit.annaPeli(5); 
    assertEquals("From: Pelit line: 153", 1, loytyneet.size()); 
    assertEquals("From: Pelit line: 154", true, loytyneet.get(0) == peli51); 
  } // Generated by ComTest END
}