package fxPepe.test;
// Generated by ComTest BEGIN
import static org.junit.Assert.*;
import org.junit.*;
import fxPepe.*;
// Generated by ComTest END

/**
 * Test class made by ComTest
 * @version 2020.02.29 02:27:34 // Generated by ComTest
 *
 */
@SuppressWarnings({ "all" })
public class PeliTest {


  // Generated by ComTest BEGIN
  /** testGetNimi27 */
  @Test
  public void testGetNimi27() {    // Peli: 27
    Peli tr2 = new Peli(); 
    tr2.taytaPeliTiedoilla(); 
    { String _l_=tr2.getNimi(),_r_="Tomb Raider 2"; if ( !_l_.matches(_r_) ) fail("From: Peli line: 30" + " does not match: ["+ _l_ + "] != [" + _r_ + "]");}
  } // Generated by ComTest END


  // Generated by ComTest BEGIN
  /** testRekisteroi111 */
  @Test
  public void testRekisteroi111() {    // Peli: 111
    Peli ra1 = new Peli(); 
    assertEquals("From: Peli line: 113", 0, ra1.getTunniste()); 
    ra1.rekisteroi(); 
    Peli ra2 = new Peli(); 
    ra2.rekisteroi(); 
    int n1 = ra1.getTunniste(); 
    int n2 = ra2.getTunniste(); 
    assertEquals("From: Peli line: 119", n2-1, n1); 
  } // Generated by ComTest END
}