package fxPepe.test;
// Generated by ComTest BEGIN
import static org.junit.Assert.*;
import org.junit.*;
import fxPepe.*;
// Generated by ComTest END

/**
 * Test class made by ComTest
 * @version 2020.02.29 02:23:45 // Generated by ComTest
 *
 */
@SuppressWarnings({ "all" })
public class PeliTietoTest {



  // Generated by ComTest BEGIN
  /** testRekisteroi94 */
  @Test
  public void testRekisteroi94() {    // PeliTieto: 94
    PeliTieto ra1 = new PeliTieto(); 
    assertEquals("From: PeliTieto line: 96", 0, ra1.getPelinTunniste()); 
    ra1.rekisteroi(); 
    PeliTieto ra2 = new PeliTieto(); 
    ra2.rekisteroi(); 
    int n1 = ra1.getPelinTunniste(); 
    int n2 = ra2.getPelinTunniste(); 
    assertEquals("From: PeliTieto line: 102", n2-1, n1); 
  } // Generated by ComTest END
}