package fxPepe.test;
// Generated by ComTest BEGIN
import fxPepe.*;
import java.util.*;
import static org.junit.Assert.*;
import org.junit.*;
// Generated by ComTest END

/**
 * Test class made by ComTest
 * @version 2020.02.28 18:35:26 // Generated by ComTest
 *
 */
@SuppressWarnings({ "all" })
public class PeliTiedotTest {



  // Generated by ComTest BEGIN
  /** testIterator74 */
  @Test
  public void testIterator74() {    // PeliTiedot: 74
    PeliTiedot tiedot = new PeliTiedot(); 
    PeliTieto tieto21 = new PeliTieto(2); tiedot.lisaa(tieto21); 
    PeliTieto tieto11 = new PeliTieto(1); tiedot.lisaa(tieto11); 
    PeliTieto tieto22 = new PeliTieto(2); tiedot.lisaa(tieto22); 
    PeliTieto tieto12 = new PeliTieto(1); tiedot.lisaa(tieto12); 
    PeliTieto tieto23 = new PeliTieto(2); tiedot.lisaa(tieto23); 
    Iterator<PeliTieto> i2=tiedot.iterator(); 
    assertEquals("From: PeliTiedot line: 86", tieto21, i2.next()); 
    assertEquals("From: PeliTiedot line: 87", tieto11, i2.next()); 
    assertEquals("From: PeliTiedot line: 88", tieto22, i2.next()); 
    assertEquals("From: PeliTiedot line: 89", tieto12, i2.next()); 
    assertEquals("From: PeliTiedot line: 90", tieto23, i2.next()); 
    try {
    assertEquals("From: PeliTiedot line: 91", tieto12, i2.next()); 
    fail("PeliTiedot: 91 Did not throw NoSuchElementException");
    } catch(NoSuchElementException _e_){ _e_.getMessage(); }
    int n = 0; 
    int pnrot[] = { 2,1,2,1,2} ; 
    for ( PeliTieto tieto:tiedot ) {
    assertEquals("From: PeliTiedot line: 97", pnrot[n], tieto.getPeliTietoTunniste); n++; 
    }
    assertEquals("From: PeliTiedot line: 100", 5, n); 
  } // Generated by ComTest END


  // Generated by ComTest BEGIN
  /** testAnnaPeliTiedot115 */
  @Test
  public void testAnnaPeliTiedot115() {    // PeliTiedot: 115
    PeliTiedot tiedot = new PeliTiedot(); 
    PeliTieto tieto21 = new PeliTieto(2); tiedot.lisaa(tieto21); 
    PeliTieto tieto11 = new PeliTieto(1); tiedot.lisaa(tieto11); 
    PeliTieto tieto22 = new PeliTieto(2); tiedot.lisaa(tieto22); 
    PeliTieto tieto12 = new PeliTieto(1); tiedot.lisaa(tieto12); 
    PeliTieto tieto23 = new PeliTieto(2); tiedot.lisaa(tieto23); 
    PeliTieto tieto51 = new PeliTieto(5); tiedot.lisaa(tieto51); 
    List<PeliTieto> loytyneet; 
    loytyneet = tiedot.annaPeliTiedot(3); 
    assertEquals("From: PeliTiedot line: 128", 0, loytyneet.size()); 
    loytyneet = tiedot.annaPeliTiedot(1); 
    assertEquals("From: PeliTiedot line: 130", 2, loytyneet.size()); 
    assertEquals("From: PeliTiedot line: 131", true, loytyneet.get(0) == tieto11); 
    assertEquals("From: PeliTiedot line: 132", true, loytyneet.get(1) == tieto12); 
    loytyneet = tiedot.annaPeliTiedot(5); 
    assertEquals("From: PeliTiedot line: 134", 1, loytyneet.size()); 
    assertEquals("From: PeliTiedot line: 135", true, loytyneet.get(0) == tieto51); 
  } // Generated by ComTest END
}