package fxPepe.test;
// Generated by ComTest BEGIN
import static org.junit.Assert.*;
import org.junit.*;
import fxPepe.*;
// Generated by ComTest END

/**
 * Test class made by ComTest
 * @version 2020.02.29 02:27:27 // Generated by ComTest
 *
 */
@SuppressWarnings({ "all" })
public class PelitTest {



  // Generated by ComTest BEGIN
  /** 
   * testLisaa32 
   * @throws SailoException when error
   */
  @Test
  public void testLisaa32() throws SailoException {    // Pelit: 32
    Pelit pelit = new Pelit(); 
    Peli cnc = new Peli(), ra = new Peli(); 
    assertEquals("From: Pelit line: 36", 0, pelit.getLkm()); 
    pelit.lisaa(cnc); assertEquals("From: Pelit line: 37", 1, pelit.getLkm()); 
    pelit.lisaa(ra); assertEquals("From: Pelit line: 38", 2, pelit.getLkm()); 
    pelit.lisaa(cnc); assertEquals("From: Pelit line: 39", 3, pelit.getLkm()); 
    assertEquals("From: Pelit line: 40", cnc, pelit.anna(0)); 
    assertEquals("From: Pelit line: 41", ra, pelit.anna(1)); 
    assertEquals("From: Pelit line: 42", cnc, pelit.anna(2)); 
    assertEquals("From: Pelit line: 43", false, pelit.anna(1) == cnc); 
    assertEquals("From: Pelit line: 44", true, pelit.anna(1) == ra); 
    try {
    assertEquals("From: Pelit line: 45", cnc, pelit.anna(3)); 
    fail("Pelit: 45 Did not throw IndexOutOfBoundsException");
    } catch(IndexOutOfBoundsException _e_){ _e_.getMessage(); }
    pelit.lisaa(cnc); assertEquals("From: Pelit line: 46", 4, pelit.getLkm()); 
    pelit.lisaa(cnc); assertEquals("From: Pelit line: 47", 5, pelit.getLkm()); 
    try {
    pelit.lisaa(cnc); 
    fail("Pelit: 48 Did not throw SailoException");
    } catch(SailoException _e_){ _e_.getMessage(); }
  } // Generated by ComTest END
}