package fxPepe.test;
// Generated by ComTest BEGIN
import java.util.*;
import static org.junit.Assert.*;
import org.junit.*;
import fxPepe.*;
// Generated by ComTest END

/**
 * Test class made by ComTest
 * @version 2020.03.17 02:53:43 // Generated by ComTest
 *
 */
@SuppressWarnings({ "all" })
public class PepeTest {


  // Generated by ComTest BEGIN
  /** 
   * testLisaa42 
   * @throws SailoException when error
   */
  @Test
  public void testLisaa42() throws SailoException {    // Pepe: 42
    Pepe pepe = new Pepe(); 
    Peli cnc = new Peli(), d2 = new Peli(); 
    cnc.rekisteroi(); d2.rekisteroi(); 
    assertEquals("From: Pepe line: 47", 0, pepe.getPeleja()); 
    pepe.lisaa(cnc); assertEquals("From: Pepe line: 48", 1, pepe.getPeleja()); 
    pepe.lisaa(d2); assertEquals("From: Pepe line: 49", 2, pepe.getPeleja()); 
    pepe.lisaa(cnc); assertEquals("From: Pepe line: 50", 3, pepe.getPeleja()); 
    assertEquals("From: Pepe line: 51", 3, pepe.getPeleja()); 
    assertEquals("From: Pepe line: 52", cnc, pepe.annaPeli(0)); 
    assertEquals("From: Pepe line: 53", d2, pepe.annaPeli(1)); 
    assertEquals("From: Pepe line: 54", cnc, pepe.annaPeli(2)); 
    try {
    assertEquals("From: Pepe line: 55", cnc, pepe.annaPeli(3)); 
    fail("Pepe: 55 Did not throw IndexOutOfBoundsException");
    } catch(IndexOutOfBoundsException _e_){ _e_.getMessage(); }
    pepe.lisaa(cnc); assertEquals("From: Pepe line: 56", 4, pepe.getPeleja()); 
    pepe.lisaa(cnc); assertEquals("From: Pepe line: 57", 5, pepe.getPeleja()); 
    try {
    pepe.lisaa(cnc); 
    fail("Pepe: 58 Did not throw SailoException");
    } catch(SailoException _e_){ _e_.getMessage(); }
  } // Generated by ComTest END


  // Generated by ComTest BEGIN
  /** testAnnaPeliTiedot99 */
  @Test
  public void testAnnaPeliTiedot99() {    // Pepe: 99
    Pepe p = new Pepe(); 
    Peli g1 = new Peli(), g2 = new Peli(), g3 = new Peli(); 
    g1.rekisteroi(); g2.rekisteroi(); g3.rekisteroi(); 
    int id1 = g1.getTunniste(); 
    int id2 = g2.getTunniste(); 
    PeliTieto tieto11 = new PeliTieto(id1); p.lisaa(tieto11); 
    PeliTieto tieto12 = new PeliTieto(id1); p.lisaa(tieto12); 
    PeliTieto tieto21 = new PeliTieto(id2); p.lisaa(tieto21); 
    PeliTieto tieto22 = new PeliTieto(id2); p.lisaa(tieto22); 
    PeliTieto tieto23 = new PeliTieto(id2); p.lisaa(tieto23); 
    List<PeliTieto> loytyneet; 
    loytyneet = p.annaPeliTiedot(g3); 
    assertEquals("From: Pepe line: 115", 0, loytyneet.size()); 
    loytyneet = p.annaPeliTiedot(g1); 
    assertEquals("From: Pepe line: 117", 2, loytyneet.size()); 
    assertEquals("From: Pepe line: 118", true, loytyneet.get(0) == tieto11); 
    assertEquals("From: Pepe line: 119", true, loytyneet.get(1) == tieto12); 
    loytyneet = p.annaPeliTiedot(g2); 
    assertEquals("From: Pepe line: 121", 3, loytyneet.size()); 
    assertEquals("From: Pepe line: 122", true, loytyneet.get(0) == tieto21); 
  } // Generated by ComTest END
}