package fxPepe.test;
// Generated by ComTest BEGIN
import static org.junit.Assert.*;
import org.junit.*;
import fxPepe.*;
// Generated by ComTest END

/**
 * Test class made by ComTest
 * @version 2020.02.24 23:36:50 // Generated by ComTest
 *
 */
@SuppressWarnings({ "all" })
public class PepeTest {



  // Generated by ComTest BEGIN
  /** 
   * testLisaa38 
   * @throws SailoException when error
   */
  @Test
  public void testLisaa38() throws SailoException {    // Pepe: 38
    Pepe pepe = new Pepe(); 
    Peli cnc = new Peli(), d2 = new Peli(); 
    cnc.rekisteroi(); d2.rekisteroi(); 
    assertEquals("From: Pepe line: 43", 0, pepe.getPeleja()); 
    pepe.lisaa(cnc); assertEquals("From: Pepe line: 44", 1, pepe.getPeleja()); 
    pepe.lisaa(d2); assertEquals("From: Pepe line: 45", 2, pepe.getPeleja()); 
    pepe.lisaa(cnc); assertEquals("From: Pepe line: 46", 3, pepe.getPeleja()); 
    assertEquals("From: Pepe line: 47", 3, pepe.getPeleja()); 
    assertEquals("From: Pepe line: 48", cnc, pepe.annaPeli(0)); 
    assertEquals("From: Pepe line: 49", d2, pepe.annaPeli(1)); 
    assertEquals("From: Pepe line: 50", cnc, pepe.annaPeli(2)); 
    try {
    assertEquals("From: Pepe line: 51", cnc, pepe.annaPeli(3)); 
    fail("Pepe: 51 Did not throw IndexOutOfBoundsException");
    } catch(IndexOutOfBoundsException _e_){ _e_.getMessage(); }
    pepe.lisaa(cnc); assertEquals("From: Pepe line: 52", 4, pepe.getPeleja()); 
    pepe.lisaa(cnc); assertEquals("From: Pepe line: 53", 5, pepe.getPeleja()); 
    try {
    pepe.lisaa(cnc); 
    fail("Pepe: 54 Did not throw SailoException");
    } catch(SailoException _e_){ _e_.getMessage(); }
  } // Generated by ComTest END
}