package fxPepe.test;
// Generated by ComTest BEGIN
import static org.junit.Assert.*;
import org.junit.*;
import fxPepe.*;
// Generated by ComTest END

/**
 * Test class made by ComTest
 * @version 2020.02.29 02:39:44 // Generated by ComTest
 *
 */
@SuppressWarnings({ "all" })
public class TietorakenneTest {
}